### ISSUE TITLE
Referencing error for BITBOX.Address.details()

### ISSUE THREAD

**Issue by alwaysAn0n** [Bitcoin-com/bitbox-javascript-sdk#6]
`Bitbox-cli` is occasionally throwing inside of the `Address.details` method.  While that error is caught in the `.catch`, it throws again (uncaught) because it attempts to reference a missing property on the callback parameter.  Below is the exact error message where I first noticed it.  It doesn't do it consistently but I did manage to force it using the code at the bottom.

Since the same method is used to catch other errors throughout the library, it's possible this problem is occurring for other methods as well.  I'll update if I find more.

```
Failed to fetch addressDetails for [ 'bitcoincash:qpc2hxhqllxhfyv7hv5u2zytsf52v2s9nv2p597vxw' ] : TypeError: Cannot read property 'message' of undefined
at /app/node_modules/bitbox-cli/lib/Address.js:155:57
at <anonymous>
2018-07-30T09:55:31.023741+00:00 app[worker.1]: at process._tickCallback (internal/process/next_tick.js:188:7)
```

You can force it by including an undefined element in the address array.

```
let oneOrMoreCashAddresses = [ 'bitcoincash:qpc2hxhqllxhfyv7hv5u2zytsf52v2s9nv2p597vxw', undefined];

BITBOX
.Address
.details(oneOrMoreCashAddresses)
.catch(console.log)
.then(function(addressDetails) {
  console.log(addressDetails);
});

```

**Comment by cgcardona** [comment]
I refactored error handling. Can you see if this is still a problem for you in v1.6.3? Thanks

**Comment by christroutner** [comment]
Closing this due to inactivity. Error handling has been updated and it's an issue we're continuing to monitor. Please open a new issue if there are continued problems with error handling.
